@host=http://localhost:3000/books


GET {{ host }} HTTP/1.1
###

GET {{ host }}/14 HTTP/1.1
###

POST {{ host }} HTTP/1.1
Content-Type: application/json

{
    "title": "Rayuela",
    "author": "Julio Cortázar",
    "year": 1963,
    "isbn": "9788437604948",
    "stock": 6
}
###

PATCH {{ host }}/19 HTTP/1.1
Content-Type: application/json

{
    "id":19,
    "title": "cenicienta",
    "author": "Mario Vargas Llosa",
    "year": 1444,
    "isbn": "9788432223882",
    "stock": 9
}
###

DELETE {{ host }}/19 HTTP/1.1

